# Always use explicit golang and base OS version for the image
FROM 274295908850.dkr.ecr.eu-west-1.amazonaws.com/i/golang:1.21.1-alpine3.18

# Switch to generic build directory
WORKDIR /usr/src/service

# Download and verify dependencies
COPY go.mod go.sum ./
RUN go mod download && go mod verify

# Copy in source files
COPY main.go main_test.go ./

# Install and run the gocov2lcov adapter module
RUN go install github.com/jandelgado/gcov2lcov@v1.0.6

# By default, coverage is outputted in the same directory
ENV COVERAGE_DIRECTORY "."

# Create the coverage directory if it doesn't exist yet
RUN mkdir -p "${COVERAGE_DIRECTORY}"

# Test and convert to lcov style report
ENTRYPOINT GOCACHE="/usr/src/service/.cache/go-build" go test -coverprofile "${COVERAGE_DIRECTORY}/coverage.gcov.out" && gcov2lcov -infile "${COVERAGE_DIRECTORY}/coverage.gcov.out" -outfile "${COVERAGE_DIRECTORY}/coverage.lcov.out"
